### ISSUE TITLE
Letters misplaced on multiple editing

### ISSUE THREAD

**Issue by RomaricMourgues** [widmogrod/notepad-app#2]
Hello,
I tried to attach your crdt code to an Ace editor. This was working well but I discover an error case. I looked on my code and tried to change some things but I were unable to find any solution.
So I tried to have the same error on your demo (notepad-app.herokuapp.com), and finally you have the same error.

I don't know if the errors comes from the crdt code or the text-editor adapter, here is the description of how to make the error :
- Open a new document on two computers and add a vertical bar (or an other delimiter)
- Write before and after the delimiter in the same time
- Letters at the right of the delimiter are sometime misplaced

I join a gif to show you the error (look at the final order, the 6 is at the end. I wrote : 1234567890),
![ezgif com-gif-maker](https://user-images.githubusercontent.com/14353924/30493920-62aed19e-9a46-11e7-8160-ebea8922ba54.gif)

Thanks for your time, and by the way, very good work on crdt.js exactly what I needed !

**Comment by widmogrod** [comment]
@RomaricMollard thank you for detailed description It's very helpful.

There is few issues that I try to solve to eliminate this situation:
- Editor rendering
- Intent preservation

### Editor rendering
Here you can find most of UX issues. In my initial naive implementation I have listen to the `KeyboardEvent` and try to react to it. But rendering of events was done by the browser. This leads to the situation that "what you see is NOT what you get" - and when CRDTs operations from different client were received the view was re-rendered to actual state.

Only solution to this is to have something like `game loop` rendering: `fist capture events -> update model -> render`.

Unfortunately this requires to much work to build editor that work in such way from scratch, so I chose to use one of the open source editors.

Currently I'm experimenting with https://github.com/quilljs/quill. (https://github.com/widmogrod/js-crdt/issues/1). It's doing it's job, but now I must solve issue with **cursor synchronisation**.

You can try it on this branch https://github.com/widmogrod/notepad-app/tree/feature/dev-branch

### Intent preservation
I don't want to go into details, but this could help in situation when **heavily edited document** could receive operations in wrong order and therefore result in forking of vector clocks. Of course it still would converge to same state but result would be far from what user intended.

**Comment by RomaricMourgues** [comment]
Hello, ok, good to know, I'll look for and implementation with Ace anyway. They found a way with y-js library so it should be possible :)
I tell you if I found a way !

**Comment by widmogrod** [comment]
Today I have updated editor that supports multiple cursors.
<img width="442" alt="screen shot 2017-09-17 at 00 14 04" src="https://user-images.githubusercontent.com/164249/30516363-254d7f92-9b3d-11e7-9af1-f18ada368bfb.png">
